### Context

**Planet Classes**
* **Class 0:** Desert
* **Class 1:** Volcanic
* **Class 2:** Oceanic
* **Class 3:** Forest
* **Class 4:** Icy

We must create a model that learns the pattern of a planet's characteristics (such as atmospheric pressure, average temperature, etc.) and is able to classify it among the classes above based solely on these characteristics.

We receive **training** data, which already comes with *labels* (the "answer key"), and **test** data, which has no answer key and is what we have to classify and submit.

### Loading the data

In [1]:
import pandas as pd

train = pd.read_csv('./data/train.csv')
test = pd.read_csv('./data/test.csv')

In [2]:
train

,id,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,target
0,12251,38.763463,4.372530,2.888516,12.352539,18.906550,9.605924,3.456596,3.959477,4.738227,3.692509,11.192263,9.076242,4.692962,2
1,4529,32.192181,3.158109,2.134617,16.193530,26.786878,9.347958,5.093277,6.893790,3.399840,2.080853,19.486692,12.349952,3.217670,0
2,11284,28.370782,3.006067,1.969280,15.163950,28.515109,7.946870,5.609813,6.511194,3.256799,2.290993,18.405205,14.781329,3.231217,0
3,10993,38.215409,2.174232,2.935104,11.501867,18.419571,7.954005,4.229832,4.522060,4.869234,3.383514,12.782517,17.343742,5.009182,2
4,12927,38.904545,2.956164,2.253149,12.282552,25.547887,8.168776,3.653026,6.809110,4.971130,2.127363,19.247327,20.115183,3.560524,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495,6951,30.605226,2.172545,1.456766,15.916774,33.872292,7.766799,4.455944,4.866775,5.274495,3.194181,13.756923,15.133962,4.489715,4
10496,8097,37.153719,2.930280,2.514520,10.042402,22.815845,6.018057,5.359753,5.656202,3.601738,2.760592,15.988397,19.794919,3.752870,2
10497,9011,24.316856,2.771631,2.018644,16.082389,27.999121,6.014674,6.209202,4.304756,3.905507,3.502867,12.168262,6.530749,5.191197,0
10498,12617,44.748792,3.174414,1.447737,13.578811,33.966677,8.671664,4.754359,7.941178,3.325981,1.505581,22.447345,21.038993,1.795912,0
10499,14306,37.755645,3.487978,1.504204,11.137644,33.376438,6.284996,5.489823,5.570037,3.270471,2.807918,15.744835,20.531268,2.692995,0

In [3]:
test

,id,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12
0,2142,37.555079,3.205281,1.583984,11.330132,32.542511,6.581602,5.524091,5.202632,3.288405,3.009713,14.706292,20.530879,2.889453
1,3846,28.933095,3.905861,2.171001,14.644065,26.406560,9.515010,4.023027,6.528586,4.202300,2.281440,18.454367,14.862851,3.183574
2,6177,37.082903,3.259937,1.887675,12.313557,29.368109,6.533770,5.088085,5.913968,3.925079,2.619016,16.717026,16.871735,3.512345
3,11779,24.011327,4.599539,2.102587,17.349264,27.121683,12.231295,2.664319,5.226405,5.232794,2.996656,14.773491,9.133299,3.739929
4,1593,31.403592,2.543982,0.533288,14.778941,43.525198,5.225097,7.100292,4.516120,2.753415,3.386776,12.765727,16.675742,3.000528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,11496,37.789367,3.511433,2.814992,10.697124,19.675079,9.844242,3.994824,5.082404,3.762631,3.075747,14.366443,20.097503,3.278142
4496,8856,24.889203,2.508254,2.525974,15.868246,22.696114,6.931519,7.380456,6.599213,1.865822,2.242648,18.654010,10.229343,3.687254
4497,4937,39.208404,2.843656,1.975679,14.071951,28.448221,7.391533,5.525009,3.912253,3.788423,3.718447,11.058774,10.266351,4.531029
4498,7574,24.559490,2.084494,3.359952,12.531981,13.978740,6.302277,6.162282,4.496384,3.523565,3.397616,12.709938,12.636072,5.461903
4499,11780,37.584518,3.461437,2.520365,14.156093,22.754748,9.939531,5.164832,7.109487,2.612023,1.962383,20.096403,14.961472,2.578713

### Analyzing the data

Let's run `describe()`, which is a DataFrame method to see general information about the data.

In [4]:
train.drop(['target', 'id'], axis=1).describe()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12
count,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000,10500.000000
mean,34.041646,3.008547,2.270856,12.809551,25.362808,7.622088,4.929185,5.845511,3.899460,2.656615,16.523518,16.864877,3.686579
std,8.428862,0.789293,0.555685,2.809632,5.808446,1.862228,0.999776,1.278044,0.939618,0.701959,3.612650,3.882798,0.839608
min,2.334047,0.000000,0.000000,2.291309,0.000000,1.007095,0.012408,0.000000,0.000000,0.000000,0.000000,1.146293,0.000000
25%,28.314237,2.473870,1.908040,10.929376,21.674746,6.342299,4.260440,4.994872,3.250940,2.179768,14.119014,14.236178,3.109582
50%,33.597613,2.995180,2.235584,12.876576,25.731496,7.644198,4.912222,5.814415,3.914398,2.673695,16.435618,16.899192,3.644901
75%,39.444095,3.548535,2.623687,14.686464,29.155231,8.895804,5.580295,6.713698,4.542025,3.123824,18.977623,19.451122,4.270982
max,71.608174,6.333788,4.697276,24.071470,49.099531,14.146872,8.967944,10.682363,7.665165,5.867231,30.195859,33.649799,6.749778

Notice that the minimums and maximums of each column are completely unbalanced, since they are measured on different scales (almost like Celsius and Fahrenheit). 

Some have a range of [2, 71], while others have [0.01, 9], for example.

For this, we use the `StandardScaler`, responsible for making all data proportional.

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_scaled = scaler.fit_transform(train.drop(['target', 'id'], axis=1))
test_scaled = scaler.transform(test.drop(['id'], axis=1))
targets = train['target']

pd.DataFrame(train_scaled).describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,1.050000e+04,10500.000000,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04,1.050000e+04
mean,-6.090366e-16,0.000000,-2.030122e-16,-2.388777e-16,5.738478e-16,1.745905e-16,-2.084259e-16,3.254962e-16,2.057190e-16,1.170704e-16,6.746772e-16,5.017785e-16,-5.433960e-16
std,1.000048e+00,1.000048,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00,1.000048e+00
min,-3.761968e+00,-3.811880,-4.086782e+00,-3.743816e+00,-4.366747e+00,-3.552363e+00,-4.918113e+00,-4.574012e+00,-4.150245e+00,-3.784754e+00,-4.574012e+00,-4.048455e+00,-4.391042e+00
25%,-6.795321e-01,-0.677444,-6.529464e-01,-6.692208e-01,-6.349785e-01,-6.872681e-01,-6.689269e-01,-6.656106e-01,-6.902280e-01,-6.793411e-01,-6.656106e-01,-6.770438e-01,-6.872552e-01
50%,-5.268263e-02,-0.016936,-6.347740e-02,2.385658e-02,6.347740e-02,1.187340e-02,-1.696778e-02,-2.433228e-02,1.589912e-02,2.433228e-02,-2.433228e-02,8.837970e-03,-4.964262e-02
75%,6.409769e-01,0.684174,6.349785e-01,6.680599e-01,6.529464e-01,6.840070e-01,6.512868e-01,6.793411e-01,6.838899e-01,6.656106e-01,6.793411e-01,6.661093e-01,6.960749e-01
max,4.457104e+00,4.213138,4.366747e+00,4.008517e+00,4.086782e+00,3.503919e+00,4.039856e+00,3.784754e+00,4.007888e+00,4.574012e+00,3.784754e+00,4.323100e+00,3.648541e+00

Now it gets a little harder to see because of the scientific notation, but notice that all minimums are around -4 and all maximums around 4. Furthermore, the standard deviations, `std`, are all exactly equal to 1.

### Modeling and training

With the data analysis done, we can start training.

We start by creating a split of training and validation data, so we can know how well the training is going while we train.

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    train.drop(['id', 'target'], axis=1), targets, test_size=0.2, random_state=42
)

`X_train`: training data

`y_train`: training *labels*

`X_val`: validation data

`y_val`: validation *labels*

Notice that `X` is capitalized and `y` is lowercase. This happens because X is a vector (all columns of each row), and y is a number (the `target` of that row). When there is a matrix/vector, it is convention to name it in uppercase.

Now, we take our `StandardScaler` from before, and join it with our classifier in a pipeline.

Here, I chose the **MLPClassifier** (a Neural Network), but it could have been any other; this is a matter of trial and error combined with preference.

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('classifier', MLPClassifier(max_iter=1000, random_state=42))
])

pipeline

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', MLPClassifier(max_iter=1000, random_state=42))])

We train the pipeline

In [8]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', MLPClassifier(max_iter=1000, random_state=42))])

And we generate our predictions on the validation set

In [9]:
val_predictions = pipeline.predict(X_val)

### Validating the model

Finally, we just check what **F1 Score** our model received.

In [10]:
from sklearn.metrics import f1_score

print(f'F1 Score: {f1_score(y_val, val_predictions, average="weighted")}')

F1 Score: 0.8228390325109411

In this example, we ended up with **~80%** F1 score on the validation data, which would be more than enough to pass the phase in 2025.

It is important to reiterate that this is just ONE example of a solution and data analysis, among many possible ones. There were different possible analyses, more powerful models that can train for hours, or simply a little more luck (since there is a bit of randomness involved), which could have given us a better result on the test data, but the main idea here was to give a good sense of how to approach the problem.

### Submitting the answer
With everything ready, we just need to pass our data to a `.csv` file and the issue is resolved.

In [11]:
test_predictions = pipeline.predict(test.drop(['id'], axis=1))
final_dataframe = pd.DataFrame({
    'id': test['id'],
    'target': test_predictions
})

final_dataframe

         id  target
0      2142       0
1      3846       0
2      6177       0
3     11779       0
4      1593       0
...     ...     ...
4495  11496       1
4496   8856       4
4497   4937       3
4498   7574       4
4499  11780       0

[4500 rows x 2 columns]

In [12]:
final_dataframe.to_csv('submission.csv', index=False)